- name: Config VM with apps
  hosts: myhosts
  gather_facts: yes
  become: no

  tasks:
    - name: Install Growroot
      apt: name=cloud-initramfs-growroot state=present update_cache=true

    - name: Resize filesystem - Step 1
      ansible.builtin.command:
        cmd: growpart /dev/vda 1

    - name: Resize filesystem - Step 2
      ansible.builtin.command:
        cmd: resize2fs /dev/vda1

    - name: Install Cockpit
      apt: name=cockpit state=present update_cache=true

    - name: Install Slim
      apt: name=slim       state=present update_cache=true

    - name: Active Slim
      ansible.builtin.command:
        cmd: systemctl set-default graphical.target

    - name: Install Desktop
      apt: name=ubuntu-desktop      state=present update_cache=true

    - name: Download TeamViever
      ansible.builtin.command:
        cmd: wget https://dl.teamviewer.com/download/linux/version_15x/teamviewer_15.64.3_amd64.deb /srv

    - name: Install TeamViewer
      ansible.builtin.command:
        cmd: apt install /srv/teamviewer_15.64.3_amd64.deb

    - name: Install upgrades
      ansible.builtin.command:
        cmd: apt upgrade


    - name: Upgrade to newest
      ansible.builtin.command:
        cmd: do-release-upgrade -f DistUpgradeViewNonInteractive
